---
# Configure Services
- name: Copy docker-compose-ef
  template: src=docker-compose-ef.yml.j2 dest=/designsafe/docker-compose-ef.yml

- name: Set up application environment file
  template: src=designsafe.env.j2 dest=/designsafe/designsafe.env

- name: Copy systemd file designsafe-ef.service
  copy: src=designsafe-ef.service dest=/usr/lib/systemd/system/designsafe-ef.service
  notify:
    - reload systemd

- name: Enable and start designsafe-ef daemon in systemd
  service:
      enabled=yes
      name=designsafe-ef
      state=restarted

- name: Wait for Django container to be running
  wait_for: port=8000

- name: Collect Django Static Assets
  command: docker exec designsafe_fiu_ef_1 python manage.py collectstatic --noinput