---
- name: Install DesignSafe on Designsafeci-dev
  hosts: qa
  become: yes
  become_method: sudo
  vars_files:
    - /designsafe/ansible/variables/variables-qa.yml

  roles:
    - common
    - docker
    - users
    - { role: selinux, when: selinux_enabled == 'true'}
    - nginx
    - application
