---
- name: enable epel
  yum:
    name: epel-release
    state: latest

- name: upgrade all packages
  yum:
    name: *
    state: latest

- name: Install git
  yum:
    name: git
    state: present

- name: Install python
  yum:
    name: python
    state: present

- name: Install python-setuptools
  yum:
    name: python-setuptools
    state: present

- name: Install python-devel
  yum:
    name: python-devel
    state: present

- name: Install syslog
  yum:
    name: syslog

- name: Install pip
  command: easy_install pip

- name: Install virtualenv
  command: pip install virtualenv

- name: Install the 'Development tools' package group
  yum:
    name: "@Development tools"
    state: present

- name: Install nfs-utils
  yum:
    name: nfs-utils
    state: present
