---
- name: install docker requirements
  yum:
    name: "{{ item }}"
    state: present
  with_items: ["yum-utils", "device-mapper-persistent-data", "lvm2"]

- name: Add docker repository
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install docker
  yum:
    name: docker-ce
    state: present

- name: Install docker-py
  pip:
    name: docker-py

- name: Ensure docker-compose is installed and available
  get_url:
      url : https://github.com/docker/compose/releases/download/1.15.0/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
      dest: /usr/local/bin/docker-compose
      mode: 0755

- name: Enable docker daemon in systemd
  service:
    enabled: yes
    name: docker
    state: started
