---
- name: Add repository
  yum_repository:
    name: dockerrepo
    description: Docker Repository
    baseurl: https://yum.dockerproject.org/repo/main/centos/7/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://yum.dockerproject.org/gpg

- name: Install docker
  yum: name=docker-engine state=present

- name: Install docker-py
  pip: name=docker-py

- name: Ensure docker-compose is installed and available
  get_url:
      url : https://github.com/docker/compose/releases/download/1.8.0/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
      dest: /usr/local/bin/docker-compose
      mode: 0755

- name: Enable docker daemon in systemd
  service: enabled=yes name=docker state=started
