---
# Create various application directories
- name: Create designsafe directory
  file: path=/srv/www/designsafe state=directory owner=portal group=portal

- name: Create designsafe/media directory
  file: path=/srv/www/designsafe/media state=directory owner=tg458981 group=G-816877

- name: Create designsafe/static directory
  file: path=/srv/www/designsafe/static state=directory owner=tg458981 group=G-816877

- name: Create /designsafe/redis_data directory
  file: path=/srv/www/designsafe/redis_data state=directory owner=999

# Pull Application Images
#- name: Pull buildpack-deps image
#  docker_image:
#    name: buildpack-deps
#    tag: trusty
#    force: True

- name: Pull redis image
  docker_image:
    name: redis
    tag: 7
    force: True

- name: Pull memcached image
  docker_image:
    name: memcached
    tag: 1.4
    force: True
