---
# Create various application directories
- name: Create /designsafe directory
  file: path=/designsafe state=directory owner=portal group=portal

- name: Create /designsafe/media directory
  file: path=/designsafe/media state=directory owner=tg458981 group=G-80610

- name: Create /designsafe/static directory
  file: path=/designsafe/static state=directory owner=tg458981 group=G-80610

- name: Create /designsafe/redis_data directory
  file: path=/designsafe/redis_data state=directory owner=999

# Pull Application Images
- name: Pull buildpack-deps image
  docker_image:
    name: buildpack-deps
    tag: trusty
    force: True

- name: Pull redis image
  docker_image:
    name: redis
    tag: 3.2
    force: True

- name: Pull memcached image
  docker_image:
    name: memcached
    tag: 1.4
    force: True

- name: Pull rabbitmq image
  docker_image:
    name: rabbitmq:3-management
    tag: 3-management
    force: True
  when: inventory_hostname == "worker"
