---

- name: Create /designsafe directory
  file: path=/designsafe state=directory

- name: Create /designsafe/media directory
  file: path=/designsafe/media state=directory

- name: Create /designsafe/redis_data directory
  file: path=/designsafe/redis_data state=directory

- name: Create /designsafe/conf directory
  file: path=/designsafe/conf state=directory

- name: Create /corral-repl/tacc/NHERI
  mount: name=/corral-repl/tacc/NHERI src=129.114.52.21:/corral-repl/tacc/NHERI fstype=nfs opts=rw,nosuid,rsize=1048576,wsize=1048576,intr,nfsvers=3,tcp,addr=129.114.52.21 state=mounted #state=present

# - name: Create /etc/ssl/ef.designsafe-ci.org directory
#   file: path=/etc/ssl/ef.designsafe-ci.org state=directory

# - name: Create /etc/ssl/designsafe-ci.org
#   file: path=/etc/ssl/designsafe-ci.org state=directory

# - name: Copy main TLS certs
#   copy: src={{ main_TLS_loc }} dest=/etc/ssl

# - name: Copy EF TLS certs
#   copy: src={{ EF_TLS_loc }} dest=/etc/ssl

# - name: Copy systemd file designsafe.service
#   copy: src=designsafe.service dest=/usr/lib/systemd/system/designsafe.service

# - name: Copy systemd file designsafe-ef.service
#   copy: src=designsafe-ef.service dest=/usr/lib/systemd/system/designsafe-ef.service

- name: Copy designsafe ENV
  template: src=designsafe.env.j2 dest=/designsafe/designsafe.env
  notify:
    - restart designsafe

- name: Copy docker-compose
  template: src=docker-compose-native.yml.j2 dest=/designsafe/docker-compose.yml
  notify:
    - restart designsafe

# - name: Copy docker-compose-ef
#   copy: src=docker-compose-native-ef.yml dest=/designsafe/docker-compose-ef.yml
#   # notify:
#   #   - restart uwsgi

- name: Clone 'DesignSafe-CI/portal' repository
  git: repo=https://github.com/DesignSafe-CI/portal.git dest=/designsafe/portal version={{ version }}
  register: repo_updated
  notify:
    - restart designsafe

- name: Build docker image
  command:
      docker build -t designsafeci/portal:{{version}} /designsafe/portal
  when: repo_updated|changed

- name: Copy systemd file designsafe.service
  copy: src=designsafe.service dest=/usr/lib/systemd/system/designsafe.service
  notify:
    - reload systemd
    - restart designsafe

- name: Enable and start designsafe daemon in systemd
  service:
      enabled=yes
      name=designsafe
      state=started

# - name: run collectstatic
#   command: docker exec -it designsafe_django_1 python manage.py collectstatic --noinput