---
- name: Copy systemd file designsafe-ef.service
  copy: src=designsafe-ef.service dest=/usr/lib/systemd/system/designsafe-ef.service
  notify:
    - reload systemd
    - restart designsafe-ef

- name: Create /etc/ssl/ef.designsafe-ci.org directory
  file: path=/etc/ssl/ef.designsafe-ci.org state=directory

- name: Copy docker-compose-ef
  copy: src=docker-compose-native-ef.yml dest=/designsafe/docker-compose-ef.yml

- name: Enable and start designsafe-ef daemon in systemd
  service:
      enabled=yes
      name=designsafe-ef
      state=started
