---
# Configure Services
- name: Copy docker-compose file
  template: src=docker-compose.yml.j2 dest=/srv/www/designsafe/docker-compose.yml
  when: inventory_hostname == "portal-prod" or inventory_hostname == "portal-dev"

- name: Copy docker-compose-worker file
  template: src=docker-compose-worker.yml.j2 dest=/srv/www/designsafe/docker-compose.yml
  when: inventory_hostname == "worker-prod" or inventory_hostname == "worker-dev"

- name: Set up application environment file
  template: src=designsafe.env.j2 dest=/srv/www/designsafe/designsafe.env

- name: Copy google JSON settings
  template:
    src: google_client_secrets.json.j2
    dest: /srv/www/designsafe/client_secrets.json

- name: Copy External Resource Secrets
  template:
    src: external_resource_secrets.j2
    dest: /srv/www/designsafe/external_resource_secrets.py

- name: Create conf path
  file: path=/srv/www/designsafe/conf state=directory owner=portal group=portal

- name: Create uwsgi conf path
  file: path=/srv/www/designsafe/conf/uwsgi state=directory owner=portal group=portal

- name: Copy UWSGI ini file
  template:
    src: uwsgi.ini.j2
    dest: "{{uwsgi.ini_path}}"

- name: Run docker-compose up
  command: docker-compose -f /srv/www/designsafe/docker-compose.yml up -d
  #  docker_service:
  #      project_src: /srv/www/designsafe
  #      pull: true
  #      state: present
  #
- name: Wait for Django container to be running
  wait_for: port=8000
  when: (inventory_hostname != 'worker-prod' and inventory_hostname != 'worker-dev') and
         'vagrant' not in group_names

- name: Run Django migrations
  command: docker exec -u tg458981 designsafe_django_1  python manage.py migrate
  when: (inventory_hostname != "worker-prod" and inventory_hostname != "worker-dev") and
         'vagrant' not in group_names

- name: Run Django collectstatic
  command: docker exec -u tg458981 designsafe_django_1 python manage.py collectstatic -c --noinput -i *babel* -i rxjs -i karma -i webpack -i demo -i example
  when: (inventory_hostname != "worker-prod" and inventory_hostname != "worker-dev") and
         'vagrant' not in group_names

- name: Restart uWSGI on container
  command: "docker  exec -u tg458981 designsafe_django_1 uwsgi --reload {{uwsgi.pidfile}}"
  when: (inventory_hostname != "worker-prod" and inventory_hostname != "worker-dev") and
         'vagrant' not in group_names
