---
# Nginx role assumes that any SSL/TLS certs have already been deployed to the host.

- name: Install nginx
  yum: name=nginx state=present
  when: portal_upgrade == 'true'

- name: Configure /etc/nginx/nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: Copy TLS certs
  copy: src={{ nginx_tls_certs_path }} dest=/etc/ssl
  when: "'vagrant' not in group_names"
  notify:
    - restart nginx

- name: Copy TLS certs to VM
  copy:
    src: "{{dummy_certs_path}}/{{ item }}"
    dest: "/etc/ssl/{{ item }}"
  with_items: ["dummy.crt", "dummy.key"]
  when: "'vagrant' in group_names"

- name: Copy gzip.conf configuration to /etc/nginx/
  copy: src=gzip.conf dest=/etc/nginx/gzip.conf
  notify:
    - restart nginx

- name: Create dhparam.pem
  command: openssl dhparam -out /etc/ssl/dhparam.pem 2048 creates=/etc/ssl/dhparam.pem

- name: Copy error pages
  copy: src=error dest=/usr/share/nginx/html
