---
- name: Install nginx
  yum: name=nginx state=present

- name: Configure /etc/nginx/nginx.conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: Copy TLS certs
  copy: src={{ nginx_tls_certs_path }} dest=/etc/ssl
  notify:
    - restart nginx

- name: Copy gzip.conf configuration to /etc/nginx/
  copy: src=gzip.conf dest=/etc/nginx/gzip.conf
  notify:
    - restart nginx

- name: Create dhparam.pem
  command: openssl dhparam -out /etc/ssl/dhparam.pem 2048 creates=/etc/ssl/dhparam.pem

- name: Copy error pages
  copy: src=error dest=/usr/share/nginx/html
