---
# - name: Install uwsgi #part of build
#   pip: name=uwsgi state=latest

# - name: Create /etc/uwsgi
#   file: path=/etc/uwsgi state=directory

# - name: Copy uwsgi.ini
#   copy: src=uwsgi.ini dest=/etc/uwsgi/uwsgi.ini
#   notify:
#     - restart uwsgi

# - name: Copy uwsgi_websocket.ini
#   copy: src=uwsgi_websocket.ini dest=/etc/uwsgi/uwsgi_websocket.ini
#   notify:
#     - restart uwsgi

# - name: Copy systemd file designsafe.service
#   # copy: src=designsafe.service dest=/etc/systemd/system/designsafe.service #why does this one work?
#   copy: src=designsafe.service dest=/usr/lib/systemd/system/designsafe.service #gives permission denied?

# - name: Copy systemd file designsafe-ef.service
#   # copy: src=designsafe-ef.service dest=/etc/systemd/system/designsafe-ef.service
#   copy: src=designsafe-ef.service dest=/usr/lib/systemd/system/designsafe-ef.service

# - name: Build docker image #works
#   command:
#        docker build -t designsafeci/portal:latest .
#   args:
#        chdir: /designsafe/portal

# - name: Build docker image #works
#   command:
#        docker build -t designsafeci/portal:latest /designsafe/portal

# - name: Build docker image
#   command:
#       # docker-compose build
#       docker-compose -f /designsafe/docker-compose.yml build
#   # args:
#   #     chdir: /designsafe
#   # become: yes
#   # become_user: root

# - name: build image
#   docker_image:
#     path: /designsafe/portal
#     state: present
#     force: yes
#     name: designsafeci/portal
#     tag: designsafeci/portal:latest

# - name: Build docker containers
#   tasks:
#     - docker_service:
#         project_src: /designsafe
#         build: yes
      # register: output

# - name: Enable uWSGI daemon in systemd
#   service:
#       enabled=yes
#       name=uwsgi
#       state=started


# - name: Enable and start designsafe daemon in systemd
#   service:
#       enabled=yes
#       name=designsafe
#       state=started

# - name: Enable and start designsafe-ef daemon in systemd
#   service:
#       enabled=yes
#       name=designsafe-ef
#       state=started