data:
  image: buildpack-deps:trusty
  volumes:
    - /designsafe/static:/var/www/designsafe-ci.org/static
    - /designsafe/media:/var/www/designsafe-ci.org/media
    - /designsafe/redis_data:/data

redis:
  image: redis
  command: redis-server --appendonly yes
  volumes_from:
    - data

memcached:
  image: memcached

worker:
  image: designsafeci/portal
  env_file: designsafe.env
  log_driver: syslog
  log_opt:
    syslog-tag: worker
  links:
    - redis:redis
    - memcached:memcached
  volumes_from:
    - data
  command: ./bin/run-celery.sh

websocket:
  image: designsafeci/portal
  env_file: designsafe.env
  log_driver: syslog
  log_opt:
    syslog-tag: websocket
  ports:
    - 9000:9000
  links:
    - redis:redis
    - memcached:memcached
  volumes_from:
    - data
  command: uwsgi --ini /portal/conf/uwsgi_websocket.ini

django:
  image: designsafeci/portal
  env_file: designsafe.env
  log_driver: syslog
  log_opt:
    syslog-tag: main
  ports:
    - 8000:8000
  links:
    - redis:redis
    - memcached:memcached
  volumes_from:
    - data
