---
- name: Copy External resource secret dummy.
  copy: src=files/external_resource_secrets.py dest=/home/designsafe/portal/designsafe/settings/external_resource_secrets.py

- name: Checkout DesignSafe-CI/portal.git repository
  git:
    repo: https://github.com/designsafe-ci/portal.git
    dest: /home/designsafe/portal
    version: '{{version}}'

- name: Login to Docker Hub
  docker_login:
    username: '{{docker_login.username}}'
    password: '{{docker_login.password}}'
    email: '{{docker_login.email}}'

- name: Build Docker Image
  docker_image:
    path: /home/designsafe/portal
    name: designsafeci/portal
    tag: '{{version}}'
    dockerfile: conf/docker/Dockerfile
    repository: designsafeci/portal

- name: Push Docker Image
  docker_image:
    name: designsafeci/portal
    tag: '{{version}}'
    push: yes 
