---
- name: Checkout DesignSafe-CI/portal.git repository
  git: repo=https://github.com/designsafe-ci/portal.git dest=/src/designsafe/portal version={{ version }}

- name: Build Docker Image
  docker_image: path=/src/designsafe/portal/ name=designsafeci/portal repository=docker.designsafe-ci.org tag={{ version }} force=yes
