---
- name: Checkout DesignSafe-CI/portal.git repository
  git:
    repo: https://github.com/designsafe-ci/portal.git
    dest: /home/designsafe/portal
    version: '{{version}}'
  delegate_to: localhost

- name: Login to Docker Hub
  docker_login:
    username: '{{docker_login.username}}'
    password: '{{docker_login.password}}'
    email: '{{docker_login.email}}'
  delegate_to: localhost

- name: Build Docker Image
  docker_image:
    path: /home/designsafe/portal
    name: designsafeci/portal
    tag: '{{version}}'
    dockerfile: conf/docker/Dockerfile
    repository: designsafeci/portal
  delegate_to: localhost

- name: Push Docker Image
  docker_image:
    name: designsafeci/portal
    tag: '{{version}}'
    push: yes 
  delegate_to: localhost
