---
- name: Install DesignSafe on Edge
  hosts: edge
  become: yes
  become_method: sudo

  roles:
    - common
    - docker
    - users
    - { role: selinux, when: selinux_enabled == 'true'}
    - nginx
    - application
    - ef
    - systemd
