---
- name: Install DesignSafe Main Portal
  hosts: designsafe_portal_qa
  vars_files:
    - ~/.ansible/designsafe/vars/portal_qa.yml

  roles:
    - common
    - docker
    - users
    - { role: selinux, when: selinux_enabled == 'false'}
    - nginx
    - portal_common
    - portal_main
