---
- name: Install DesignSafe on rodeo
  hosts: rodeo
  become: yes
  become_method: sudo

  roles:
    - common
    - docker
    - users
    - { role: selinux, when: selinux_enabled == 'true'}
    - nginx
    - application
